renting/renting/website/comment/urls.py
from django.urls import path,include
from . import views
from user_info import views as user_info_views
urlpatterns = [
            path('comment/', views.comment, name='comment'),
            path('login/',user_info_views.login,name='login'),
            #path('user_info/',include('user_info.urls')),
            path('update_comment/',views.update_comment,name='update_comment'),
]

renting/renting/website/user_info/urls.py
from django.urls import path
from . import views

urlpatterns = [

	path('register/', views.register, name='register'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),
	path('user_info/', views.user_info, name='user_info'),
	path('change_nickname/', views.change_nickname, name='change_nickname'),
	path('change_pwd/', views.change_pwd, name='change_pwd'),
	path('bind_email/', views.bind_email, name='bind_email'),
	path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
	path('forgot_pwd/', views.forgot_pwd, name='forgot_pwd'),

]

renting/renting/website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('user_info/',include('user_info.urls')),
    path('property/', include('property.urls')),
    path('comment/',include('comment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

renting/renting/website/user_info/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    nickname = models.CharField(max_length = 100)

    def __str__(self):
        return '<Profile: %s for %s>' % (self.nickname, self.user.username)



# 只是简化profile在前端使用，编写前端可以直接使用两个方法判断

def get_nickname(self):
    if Profile.objects.filter(user = self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return self.username

def has_nickname(self):
    return Profile.objects.filter(user = self).exists()

User.get_nickname= get_nickname
User.has_nickname= has_nickname

renting/renting/website/user_info/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username_or_email = forms.CharField(label='username/email',
                               widget=forms.TextInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input your username/email',
                                     'required': True}),
                               min_length=3)

    password = forms.CharField(label='password', widget=forms.PasswordInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input your password',
                                     'required': True}),
                               max_length=16, min_length=3)

    def clean(self):

        username_or_email = self.cleaned_data['username_or_email']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username_or_email, password=password)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if user is not None:
                    self.cleaned_data['user'] = user
                    return self.cleaned_data

            raise forms.ValidationError('Wrong username/password')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


# 注册
class RegForm(forms.Form):

    username = forms.CharField(label='username',
                               widget=forms.TextInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input your username',
                                     'required': True}),
                               max_length=16, min_length=3)

    password = forms.CharField(label='password',
                               widget=forms.PasswordInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input your password',
                                     'required': True}),
                               max_length=16, min_length=3)

    confirm_password = forms.CharField(label='confirm password',
                               widget=forms.PasswordInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input your password again',
                                     'required': True}),
                               max_length=16, min_length=3)

    email = forms.EmailField(label='email',
                                widget=forms.EmailInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input email address',
                                    'required': True}))

    verification_code = forms.CharField(
                                label='verify code',
                                required=False,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Please press send code to receive verify code'}
                                )
                            )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(RegForm, self).__init__(*args, **kwargs)

    def clean(self):

        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username already exises')

        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password and confirm_password:
            if password != confirm_password:
                raise forms.ValidationError('Different passwords are input, try again')

        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email has been registered')

        # 判断验证码是否正确
        code = self.request.session.get('register_email_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('Wrong verify code')

        return self.cleaned_data


class ChangeNicknameForm(forms.Form):
    nickname_new = forms.CharField(label='nickname',
                               widget=forms.TextInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input your nickname'}),
                                   max_length=15)

    def __init__(self,*args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNicknameForm,self).__init__(*args, **kwargs)

    def clean(self):
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('You did not log in yet')
        return self.cleaned_data

    def clean_nickname_new(self):
        nickname_new = self.cleaned_data.get('nickname_new','').strip()
        if nickname_new == '':
            raise ValidationError("Empty new nickname")
        return nickname_new


class ChangePwdForm(forms.Form):

    old_pwd = forms.CharField(label='old_pwd',
                               widget=forms.PasswordInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input your original password'}),
                               max_length=16, min_length=3)
    new_pwd = forms.CharField(label='new_pwd',
                               widget=forms.PasswordInput(attrs=
                                    {'class': 'form-control', 'placeholder': 'Please input your new password'}),
                               max_length=16, min_length=3)

    def clean(self):
        new_pwd = self.cleaned_data.get('new_pwd','')
        if new_pwd == '':
            raise forms.ValidationError('Password cannot be empty')

    def __init__(self,*args,**kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangePwdForm, self).__init__(*args,**kwargs)

    def clean_old_pwd(self):
        old_pwd = self.cleaned_data.get('old_pwd','')
        if not self.user.check_password(old_pwd):
            raise ValidationError('Wrong original password')
        return old_pwd


class BindEmailForm(forms.Form):
    email = forms.EmailField(
        label='email',
        widget=forms.EmailInput(
           attrs={'class': 'form-control','placeholder': 'Please input correct email address'}
       )
    )

    verification_code = forms.CharField(
        label='verify code',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Please press send code to receive verify code'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断是否登陆
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('You did not log in yet')

        # 判断邮箱是否已经绑定
        if self.request.user.email != '':
            raise forms.ValidationError('Already bind email')

        # 判断验证码是否正确
        code = self.request.session.get('bind_email_code', '')
        verification_code = self.cleaned_data.get('verification_code','').strip()
        if not(code != '' and code == verification_code):
            raise forms.ValidationError('Wrong verify code')
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email has been bind')
        return email


class ForgotPwdForm(forms.Form):
    email = forms.EmailField(
        label='email',
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'Please enter your bound email'}
        )
    )

    verification_code = forms.CharField(
        label='verify code',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Please press send code to receive verify code'}
        )
    )

    new_pwd = forms.CharField(label='new_pwd',
                              widget=forms.PasswordInput(attrs=
                                                         {'class': 'form-control',
                                                          'placeholder': 'Please input your new password',
                                                          'required': False}),
                              max_length=16, min_length=3)

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgotPwdForm, self).__init__(*args, **kwargs)

    def clean(self):

        #判断邮箱是否存在
        email = self.cleaned_data['email'].strip()
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email not exists')

        # 判断验证码是否正确
        code = self.request.session.get('forgot_pwd_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('Wrong verify code')

        new_pwd = self.cleaned_data['new_pwd'].strip()
        if new_pwd == '':
            raise forms.ValidationError('Password cannot be empty')

        return self.cleaned_data

renting/renting/website/user_info/views.py
import string
import random
import time
from django.shortcuts import render, redirect
from django.contrib import auth
from django.urls import reverse
from .forms import LoginForm, RegForm, ChangeNicknameForm, BindEmailForm, ChangePwdForm, ForgotPwdForm
from django.contrib.auth.models import User
from .models import Profile
from django.http import JsonResponse
from django.core.mail import send_mail


def login(request):
    # 提交数据 login验证 操作
    if request.method == 'POST':

        # 带提交数据 错误的话forms.clean会处理
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = login_form.cleaned_data['user']
            auth.login(request, user)
            return redirect(request.GET.get('from', reverse('home')))

    # 加载数据
    else:
        # 空的
        login_form = LoginForm()

    context = dict()
    context['login_form'] = login_form
    return render(request, 'login.html', context)


# 如果post 取出来实例化 不是post直接实例化
def register(request):

    if request.method == 'POST':

        # 带提交数据 错误的话forms.clean会处理
        reg_form = RegForm(request.POST, request=request)
        if reg_form.is_valid():

            # 获取三个参数
            username = reg_form.cleaned_data['username']
            password = reg_form.cleaned_data['password']
            email = reg_form.cleaned_data['email']

            # 创建注册实例化
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()

            # 清除session
            del request.session['register_email_code']

            # 直接登陆
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            return redirect(request.GET.get('from', reverse('home')))

    else:
        reg_form = RegForm()

    context = dict()
    context['reg_form'] = reg_form
    return render(request, 'register.html', context)


def logout(request):
    auth.logout(request)
    return redirect('home')


def user_info(request):
    context = {}
    return render(request, 'user_info.html',context)


def change_nickname(request):
    if request.method == 'POST':
        form = ChangeNicknameForm(request.POST, user=request.user)
        if form.is_valid():
            nickname_new = form.cleaned_data['nickname_new']
            profile, created =Profile.objects.get_or_create(user=request.user)
            profile.nickname = nickname_new
            profile.save()
            return redirect('user_info')
    else:
        form = ChangeNicknameForm()
    context = dict()
    context['change_nickname'] = form
    return render(request, 'change_profile.html',context)


def change_pwd(request):
    if request.method == 'POST':
        form = ChangePwdForm(request.POST, user=request.user)
        if form.is_valid():
            user = request.user
            old_pwd = form.cleaned_data['old_pwd']
            new_pwd = form.cleaned_data['new_pwd']
            user.set_password(new_pwd)
            user.save()
            auth.logout(request)

            return redirect('user_info')
    else:
        form = ChangePwdForm()
    context = dict()
    context['change_pwd'] = form
    return render(request, 'change_pwd.html',context)


# request=request
def bind_email(request):

    if request.method == 'POST':

        form = BindEmailForm(request.POST, request=request)
        if form.is_valid():

            email = form.cleaned_data['email']

            request.user.email = email
            request.user.save()

            # 清除session
            del request.session['bind_email_code']

            return redirect('user_info')
    else:
        form = BindEmailForm()

    context = dict()
    context['form'] = form
    return render(request, 'bind_email.html', context)


def send_verification_code(request):
    email = request.GET.get('email', '')
    send_for = request.GET.get('send_for', '')
    data = dict()

    if email != '':
        # make the code
        code = ''.join(random.sample(string.ascii_letters + string.digits, 4))
        now = int(time.time())
        send_code_time = request.session.get('send_code_time', 0)
        if now - send_code_time < 30:
            data['status'] = 'ERROR'
        else:
            request.session[send_for] = code
            request.session['send_code_time'] = now
            # send the code
            send_mail(
                'Fake leg email',
                'Hi dear user, the verify code is: %s' % code,

                '522366853@qq.com',

                [email],
                fail_silently=False,
            )
            data['status'] = 'SUCCESS'
    else:
        data['status'] = 'ERROR'
    return JsonResponse(data)


def forgot_pwd(request):
    if request.method == 'POST':

        form = ForgotPwdForm(request.POST, request=request)
        if form.is_valid():
            email = form.cleaned_data['email']
            new_password = form.cleaned_data['new_pwd']
            user = User.objects.get(email=email)
            user.set_password(new_password)
            user.save()

            # 清除session
            del request.session['forgot_pwd_code']

            # 直接登陆
            auth.login(request, user)
            return redirect(request.GET.get('from', reverse('home')))
    else:
        form = ForgotPwdForm()

    context = dict()
    context['form'] = form
    return render(request, 'forgot_pwd.html', context)

renting/renting/website/user_info/templates/bind_email.html
{% extends 'base.html' %}

{% block title %}
Fake leg Renting|Bind email
{% endblock %}


{% block content %}
<br>
fill in the following information to bind email
<br>
    <form action="{% url 'bind_email'%}" method="POST">

        {% csrf_token %}

        {% for field in form %}
        {% if not field.is_hidden %}
            {{field.label}}
        {% endif %}

        {{field}}
        {{field.errors.as_text}}
        {% endfor %}
        <span id="tip" class="text-danger">{{form.non_field_errors}}</span>


        <button id="send_code" class="btn btn-primary">Send verify code</button>

        <input type="submit" value="Bind">

    </form>

{% endblock %}


{% block script %}


    <script type="text/javascript">

        $("#send_code").click(function(){

        var email = $("#id_email").val();
        if (email=="") {
            $("#tip").text('* The email cannot be empty');
            return false;
        }

        // 发送验证码 限制30秒内不能超过一次
        $.ajax({
            url: "{% url 'send_verification_code' %}",
            type: "GET",
            data: {
                'email': email,
                'send_for': 'bind_email_code'
                },
            cache: false,
            success: function(data){
            if(data['status']=='ERROR'){
                alter(data['status']);
            }
        }
    });
    });
    </script>

{% endblock %}

renting/renting/website/user_info/templates/change_profile.html
{% extends 'base.html' %}

{% block title %}
Fake leg Renting|Change nickname
{% endblock %}


{% block content %}
<br>
<h4>fill in the following information to change nickname</h4>
<br>

    <form action="{% url 'change_nickname'%}" method="POST">
        {% csrf_token %}

        {% for field in change_nickname %}

        {{field.label}}
        {{field}}
        {{field.errors.as_text}}
        {% endfor %}
        {{change_nickname.non_field_errors}}


        <!--!
        这里写Django form 的使用
        对应两个框：
        -->


        <input type="submit" value="Submit">
    </form>

{% endblock %}

renting/renting/website/user_info/templates/change_pwd.html
{% extends 'base.html' %}

{% block title %}
Fake leg Renting|Change password
{% endblock %}


{% block content %}
<br>
<h4>fill in the following information to change password</h4>
<br>


    <form action="{% url 'change_pwd'%}" method="POST">
        {% csrf_token %}

        {% for field in change_pwd %}

        {{field.label}}
        {{field}}
        {{field.errors.as_text}}
        {% endfor %}
        {{change_pwd.non_field_errors}}


        <!--!
        这里写Django form 的使用
        对应两个框：
        -->


        <input type="submit" value="Submit">
    </form>

{% endblock %}

renting/renting/website/user_info/templates/forgot_pwd.html
{% extends 'base.html' %}

{% block title %}
Fake leg Renting|Forgot password
{% endblock %}


{% block content %}
<br>
fill in the following information to reset password
<br>
    <form action="{% url 'forgot_pwd'%}" method="POST">

        {% csrf_token %}

        {% for field in form %}
        {% if not field.is_hidden %}
            {{field.label}}
        {% endif %}

        {{field}}
        {{field.errors.as_text}}
        {% endfor %}
        <span id="tip" class="text-danger">{{form.non_field_errors}}</span>


        <button id="send_code" class="btn btn-primary">Send verify code</button>

        <input type="submit" value="Reset">

    </form>

{% endblock %}


{% block script %}


    <script type="text/javascript">

        $("#send_code").click(function(){

        var email = $("#id_email").val();
        if (email=="") {
            $("#tip").text('* The email cannot be empty');
            return false;
        }

        // 发送验证码 限制30秒内不能超过一次
        $.ajax({
            url: "{% url 'send_verification_code' %}",
            type: "GET",
            data: {
                'email': email,
                'send_for': 'forgot_pwd_code'
                },
            cache: false,
            success: function(data){
            if(data['status']=='ERROR'){
                alter(data['status']);
            }
        }
    });
    });
    </script>

{% endblock %}

renting/renting/website/user_info/templates/login.html
{% extends 'base.html' %}

{% block title %}
Fake leg Renting|Login
{% endblock %}


{% block content %}
<br>
<h4>fill in the following information to login</h4>
<br>


    <form action="{% url 'login'%}" method="POST">
        {% csrf_token %}

        {% for field in login_form %}

        {{field.label}}
        {{field}}
        {{field.errors.as_text}}
        {% endfor %}
        {{login_form.non_field_errors}}

        <!--!
        这里写Django form 的使用
        对应两个框：
        -->


        <input type="submit" value="Submit">
    </form>




{% if not user.is_authenticated %}

<a href="{% url 'forgot_pwd' %}">Forgot password?</a>

{% endif %}
{% endblock %}

renting/renting/website/user_info/templates/register.html
{% extends 'base.html' %}

{% block title %}
Fake leg Renting|Register
{% endblock %}


{% block content %}
<br>
<h4>fill in the following information to register</h4>
<br>

    <form action="{% url 'register'%}" method="POST">

        {% csrf_token %}

        {% for field in reg_form %}

        {{field.label}}
        {{field}}

        {% endfor %}
        {{reg_form.non_field_errors}}

        <!--!
        这里写Django form 的使用
        对应两个框：
        -->

        <button id="send_code" class="btn btn-primary pull-left">Send verify code</button>

        <input type="submit" value="Submit">
    </form>
{% endblock %}




{% block script %}


    <script type="text/javascript">

        $("#send_code").click(function(){

        var email = $("#id_email").val();
        if (email=="") {
            $("#tip").text('* The email cannot be empty');
            return false;
        }

        // 发送验证码 限制30秒内不能超过一次
        $.ajax({
            url: "{% url 'send_verification_code' %}",
            type: "GET",
            data: {
                'email': email,
                'send_for': 'register_email_code'
                },
            cache: false,
            success: function(data){
            if(data['status']=='ERROR'){
                alter(data['status']);
            }
        }
    });
    });
    </script>

{% endblock %}

renting/renting/website/user_info/templates/user_info.html
{% extends 'base.html' %}

{% block title %}
Fake leg Renting|User Profile
{% endblock %}


{% block content %}

    <li></h1>Personal profile</h1></li>
    </h2>{{user.username}}</h2>


<li>nickname:{{ user.get_nickname }} <a href="{% url 'change_nickname' %}">change nickname</a></li>

<li>password: <a href="{% url 'change_pwd' %}">change password</a></li>

<li>{% if user.email %}email:{{ user.email }}
    {% else %}No email bind, email is the only way to reset password, please bind email as soon as possible<a href="{% url 'bind_email' %}">bind email</a>{% endif %}</li>

 <form method="post" action="{% url 'post_form' user.id %}"> 
    {%csrf_token%}
    <input type="submit" value="Post New Property">


{% endblock %}